name: Python Review

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit
      
      - name: Run Ruff
        run: |
          echo "## Ruffによるコードスタイルチェック" > ruff.log
          ruff check . >> ruff.log 2>&1 || true

      - name: Run Black
        run: |
          echo "## Blackによるコードフォーマットチェック" > black.log
          black --check --diff . >> black.log 2>&1 || true

      - name: Run MyPy
        run: |
          echo "## MyPyによる型チェック" > mypy.log
          mypy --show-error-codes --show-column-numbers --show-error-context src/example/bad_code.py >> mypy.log 2>&1 || true

      - name: Run Bandit
        run: |
          echo "## Banditによるセキュリティチェック" > bandit.log
          bandit -r -f txt --severity-level low src/example/bad_code.py >> bandit.log 2>&1 || true

      - name: Combine Reports
        run: |
          echo "# Pythonコードレビュー結果" > review.log
          echo "" >> review.log
          cat ruff.log black.log mypy.log bandit.log >> review.log
      
      - name: Post review comment
        if: failure()
        run: gh pr comment --body-file review.log "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
