name: Python Review

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit
      
      - name: Run checks
        run: |
          echo "## Pythonコードレビュー結果" > review.log
          
          # Ruff
          echo -e "\n### Ruff Linter" >> review.log
          ruff check . >> review.log 2>&1
          
          # Black
          echo -e "\n### Black Formatter" >> review.log
          black --check --diff . >> review.log 2>&1
          
          # MyPy
          echo -e "\n### MyPy Type Checker" >> review.log
          mypy --show-error-codes --show-column-numbers --show-error-context src/example/bad_code.py >> review.log 2>&1 || true
          
          # Bandit
          echo -e "\n### Bandit Security Check" >> review.log
          bandit -r -f txt --severity-level low src/example/bad_code.py >> review.log 2>&1 || true
      
      - name: Post review comment
        if: failure()
        run: gh pr comment --body-file review.log "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
