name: Python Review

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy
          
      - name: Run Ruff linter
        run: ruff check .
        
      - name: Run Black formatter check
        run: black --check .
        
      - name: Run MyPy type checker
        run: mypy .
        
      - name: Check for security issues with Bandit
        run: |
          pip install bandit
          bandit -r . -ll
