name: Python Review

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit
      
      - name: Run Ruff
        id: ruff
        run: |
          echo "## Ruffによるコードスタイルチェック" > ruff.log
          ruff check . >> ruff.log 2>&1 || exit 1

      - name: Run Black
        id: black
        run: |
          echo "## Blackによるコードフォーマットチェック" > black.log
          black --check --diff . >> black.log 2>&1 || exit 1

      - name: Run MyPy
        id: mypy
        run: |
          echo "## MyPyによる型チェック" > mypy.log
          mypy --strict --show-error-codes --show-column-numbers --pretty src/example/bad_code.py >> mypy.log 2>&1 || exit 1

      - name: Run Bandit
        id: bandit
        run: |
          echo "## Banditによるセキュリティチェック" > bandit.log
          bandit -r -f txt -ll src/example/bad_code.py >> bandit.log 2>&1 || exit 1

      - name: Post Review Comment
        if: always()
        run: |
          {
            echo "# Pythonコードレビュー結果"
            echo ""
            echo "## 1. Ruffによるコードスタイルチェック"
            cat ruff.log
            echo ""
            echo "## 2. Blackによるコードフォーマットチェック"
            cat black.log
            echo ""
            echo "## 3. MyPyによる型チェック"
            cat mypy.log
            echo ""
            echo "## 4. Banditによるセキュリティチェック"
            cat bandit.log
          } > review.log

          gh pr comment --body-file review.log "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Post review comment
        if: failure()
        run: gh pr comment --body-file review.log "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
