name: Python Review

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit
      
      - name: Run checks
        run: |
          echo "## Pythonコードレビュー結果" > review.log
          
          # Ruff
          echo -e "\n### Ruff Linter" >> review.log
          if ! ruff check . >> review.log 2>&1; then
            echo "Ruff check failed"
            exit_code=1
          fi
          
          # Black
          echo -e "\n### Black Formatter" >> review.log
          if ! black --check . >> review.log 2>&1; then
            echo "Black check failed"
            exit_code=1
          fi
          
          # MyPy
          echo -e "\n### MyPy Type Checker" >> review.log
          if ! mypy . >> review.log 2>&1; then
            echo "MyPy check failed"
            exit_code=1
          fi
          
          # Bandit
          echo -e "\n### Bandit Security Check" >> review.log
          if ! bandit -r . -ll >> review.log 2>&1; then
            echo "Bandit check failed"
            exit_code=1
          fi
          
          exit ${exit_code:-0}
      
      - name: Post review comment
        if: failure()
        run: gh pr comment --body-file review.log "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
